# Generated by Django 3.2.9 on 2022-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220203_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='الجنس '),
        ),
    ]
