# Generated by Django 3.2.9 on 2022-02-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(verbose_name='يوم الميلاد'),
        ),
    ]
