# Generated by Django 3.2.9 on 2022-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customer_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='massageText',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='نص رسالة المعايدة'),
        ),
        migrations.DeleteModel(
            name='massage',
        ),
    ]
