# Generated by Django 3.2.9 on 2022-02-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_row_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='row_password',
        ),
    ]
