# Generated by Django 3.2.9 on 2022-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_row_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='row_password',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
