# Generated by Django 3.2.9 on 2022-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_row_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.BooleanField(default=True, verbose_name='language'),
        ),
    ]
